spring:
  application:
    name: sca
  profiles:
    include:
      - "auth"

server:
  port: 8086

logging:
  config: logback.xml
  level:
    org.hibernate: ERROR
    org.springframework.web: INFO

trusted-certificate:
  filename: "src/main/resources/TSA_CC.pem"
  time-stamp-authority: "http://ts.cartaodecidadao.pt/tsa/server"